/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feemnage;

import java.util.ArrayList;


/**
 *
 * @author vaish
 */
public class Feereceipt extends javax.swing.JFrame {

    String s="";
    
    
    public Feereceipt() {
        initComponents();}
    
     public Feereceipt(ArrayList<String> s) {
        initComponents();
     showData(s);
             }
     
     void showData(ArrayList<String> ss){
         ss.forEach((d) -> {
             s=s+d+"\n";
        });
         area.setText(s);
         
     }
   /* public void postData(){
        area.setText("**************************\n");
        area.setText(area.getText()+"      Fee Reciept         \n");
        area.setText(area.getText()+"**************************\n");

        Date obj = new Date();
        String dat = obj.toString();
        area.setText(area.getText()+"\n"+dat+"\n");
        this.area.setText("Adm no. : "+getdata[0]+"\n");
        this.area.setText("Student Name : "+getdata[1]+"\n");
        this.area.setText("Mobile no.: "+getdata[2]+"\n");
        this.area.setText("Gender : "+getdata[3]+"\n");
        this.area.setText("Course : "+getdata[4]+"\n");
        this.area.setText("Date of payment : "+getdata[5]+"\n");
        this.area.setText("Last date for payment : "+getdata[6]+"\n");
        this.area.setText("Course Fee : "+getdata[7]+"\n");
        this.area.setText("Fine : "+getdata[8]+"\n");
        this.area.setText("Total Fee : "+getdata[9]+"\n");
        
        
        
        
        try{
           area.print();
        }catch(Exception e){
            
        }
        
        */
        
        
        
        
        
        
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        area.setForeground(new java.awt.Color(10, 51, 51));
        area.setRows(5);
        area.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feereceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feereceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feereceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feereceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Feereceipt().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
